MvcProjeKampi/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace MvcProjeKampi.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm=new CategoryManager(new EfCategoryDal());
        WriterManager wm=new WriterManager(new EfWriterDal());
        public IActionResult Index()
        {
            var headingValues = hm.GetList("Category","Writer");
            return View(headingValues);
        }
        [HttpGet]
        public IActionResult AddHeading()
        {
            List<SelectListItem> categories = (from x in cm.GetList()
                                         select new SelectListItem
                                         {
                                             Text=x.CategoryName,
                                             Value=x.CategoryId.ToString(),
                                         }).ToList();
            List<SelectListItem> writer = (from x in wm.GetList()
                                           select new SelectListItem
                                           {
                                               Text = x.WriterName + " "+ x.WriterSurname,
                                               Value = x.WriterId.ToString(),
                                           }).ToList();
            ViewBag.Categories=categories;
            ViewBag.Writer=writer;
            return View();
        }
        [HttpPost]
        public IActionResult AddHeading(Heading p)
        {
            hm.HeadingAdd(p);
            return RedirectToAction("Index");

        }
      
    }
}

MvcProjeKampi/Views/Heading/AddHeading.cshtml
@model Heading
@{
    ViewData["Title"] = "AddHeading";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


<h1>Başlık Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı:")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)

        <br />
        @Html.Label("Kategori:")
        @Html.DropDownListFor(x=>x.CategoryId,(List<SelectListItem>)ViewBag.Categories,new{@class="form-control"})
       

        <br />
        @Html.Label("Yazar:")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.Writer, new { @class = "form-control" })

    
        <br />
        <button class="btn btn-info">Başlığı Ekle</button>

    </div>
}

MvcProjeKampi/Views/Heading/Index.cshtml
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    string color = "";
    
}
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Projects</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Proje İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                ID
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 30%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var heading in Model)
                        {
                            if (heading.Category.CategoryName == "Tiyatro")
                            {
                                color = "badge badge-warning";
                            }
                            else if (heading.Category.CategoryName == "Spor")
                            {
                                color = "badge badge-success";
                            }
                            else if (heading.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge-info";
                            }
                            else  
                            {
                                color = "badge badge-secondary";
                            }
                            <tr>
                            <td>
                                @heading.HeadingId
                            </td>
                            <td>
                                <a>
                                    @heading.HeadingName
                                </a>
                                <br />
                                <small>
                                    @heading.HeadingDate
                                </small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" class="table-avatar" src="@heading.Writer.WriterImage">
                                    </li>
                                </ul>
                            </td>
                            <td class="project-state">
                                <span class="@color">@heading.Category.CategoryName</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@heading.HeadingId">
                                    <i class="fas fa-folder">
                                    </i>
                                    Yazılar
                                </a>
                                <a class="btn btn-info btn-sm" href="#">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Düzenle
                                </a>
                                <a class="btn btn-danger btn-sm" href="#">
                                    <i class="fas fa-trash">
                                    </i>
                                    Sil
                                </a>
                            </td>
                        </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>
<a href="/Heading/AddHeading" class="btn btn-primary">Yeni başlık girişi</a>



@*<h2>Index</h2>
    <br />
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Başlık</th>
            <th>Kategori</th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.HeadingID</td>
                <td>@item.HeadingName</td>
                <td>@item.Category.CategoryName</td>
            </tr>
        }
    </table>
    <br />
    <a href="/Heading/AddHeading" class="btn btn-info">Yeni başlık Girişi</a>*@