MvcProjeKampi/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using BusinessLayer.ValidationRules;
using FluentValidation.Results;
namespace MvcProjeKampi.Controllers
{
    public class WriterController : Controller
    {
        WriterManager wm = new WriterManager(new EfWriterDal());
        WriterValidator validationRules = new WriterValidator();

        public IActionResult Index()
        {
            var writerValues = wm.GetList();
            return View(writerValues);
        }
        [HttpGet]
        public IActionResult AddWriter()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddWriter(Writer p)
        {
           ValidationResult result= validationRules.Validate(p);
            if (result.IsValid)
            {
                wm.WriterAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError(err.PropertyName, err.ErrorMessage);
                }
                return View(p);
            }

        }
        [HttpGet]
        public IActionResult EditWriter(int id)
        {
            var writer=wm.GetById(id);
            return View(writer);
        }
        [HttpPost]
        public IActionResult EditWriter(Writer p)
        {
            ValidationResult result = validationRules.Validate(p);
            if (result.IsValid)
            {
                wm.WriterUpdate(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError(err.PropertyName, err.ErrorMessage);
                }
            }
            return View(p);
        }
    }
}

MvcProjeKampi/Views/Writer/AddWriter.cshtml
@model Writer
@{
    ViewData["Title"] = "AddWriter";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h1>Yeni Yazar Ekleme</h1>
<br />
@using (Html.BeginForm("AddWriter","Writer",FormMethod.Post)){
    <div class="form-group">
        @Html.Label("Yazar Adı:")
        @Html.TextBoxFor(x=>x.WriterName, new{@class="form-control"})
        @Html.ValidationMessageFor(x=>x.WriterName)
        
        <br />
        @Html.Label("Yazar Soyadı:")
        @Html.TextBoxFor(x => x.WriterSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurname)
        
        <br />
        @Html.Label("Yazar Şifre:")
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPassword)
       
        <br />
        @Html.Label("Yazar Mail:")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
        
        <br />
        @Html.Label("Yazar Açıklama:")
        @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
        
        <br />
        @Html.Label("Yazar Resim:")
        @Html.TextAreaFor(x => x.WriterImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImage)
        <br />
        @Html.Label("Yazar Unvan:")
        @Html.TextAreaFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
        <br />
        <button class="btn btn-info">Yazarı Ekle</button>

    </div>
}

MvcProjeKampi/Views/Writer/EditWriter.cshtml
@model Writer
@{
    ViewData["Title"] = "EditWriter";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<br />
<h1>Yazar Düzenleme Sayfası</h1>
@using (Html.BeginForm("EditWriter", "Writer", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Yazar ID:")
        @Html.TextBoxFor(x => x.WriterId, new { @class = "form-control" })
        
        <br />
        @Html.Label("Yazar Adı:")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName)

        <br />
        @Html.Label("Yazar Soyadı:")
        @Html.TextBoxFor(x => x.WriterSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurname)

        <br />
        @Html.Label("Yazar Şifre:")
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPassword)

        <br />
        @Html.Label("Yazar Mail:")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)

        <br />
        @Html.Label("Yazar Açıklama:")
        @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)

        <br />
        @Html.Label("Yazar Resim:")
        @Html.TextAreaFor(x => x.WriterImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImage)
        <br />
        @Html.Label("Yazar Unvan:")
        @Html.TextAreaFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
        <br />
        <button class="btn btn-success">Değişiklikleri Uygula</button>
    </div>
}

MvcProjeKampi/Views/Writer/Index.cshtml
@model List<Writer>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
 
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        

        <!-- Content Wrapper. Contains page content -->
    
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Yazarlar Listesi</h1>
                        </div>
                       
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card card-solid">
                    <div class="card-body pb-0">
                        <div class="row d-flex align-items-stretch">
                            @foreach(var writer in Model){

                            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                                <div class="card bg-light">
                                    <div class="card-header text-muted border-bottom-0">
                                        @writer.WriterTitle
                                    </div>
                                    <div class="card-body pt-0">
                                        <div class="row">
                                            <div class="col-7">
                                                <h2 class="lead"><b>@writer.WriterName @writer.WriterSurname</b></h2>
                                                <p class="text-muted text-sm"><b>Hakkında: </b> @writer.WriterAbout </p>
                                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Mail:@writer.WriterMail</li>
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                </ul>
                                            </div>
                                            <div class="col-5 text-center">
                                                <img src="~/AdminLTE-3.0.4/dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="text-right">
                                            <a href="#" class="btn btn-sm bg-teal">
                                                <i class="fas fa-comments">Yazarın Başlıkları</i>
                                            </a>
                                            <a href="/Writer/EditWriter/@writer.WriterId" class="btn btn-sm btn-primary">
                                                <i class="fas fa-user"></i> Profili Düzenle
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            }
                          
                        </div>
                    </div>
                    <!-- /.card-body -->
                   
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->

            </section>
            <!-- /.content -->
        

</body>
</html>